# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Deploy Domino Jobs

on:
  push:
    branches: [ "CSE-474-configure-app-deployment-automation" ]
  pull_request:
    branches: [ "CSE-474-configure-app-deployment-automation" ]
  pull_request_target:
    branches: [ "CSE-474-configure-app-deployment-automation" ]  

permissions:
  contents: read

jobs:
  deploy-production:
      runs-on: ubuntu-latest
      environment: 'Production'
      steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest dominodatalab
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Deploy to Domino Production
        run: |
          python src/cicd/cicd-apps.py ${{ vars.DOMINO_MODEL_OP }} ${{ vars.DOMINO_PROJECT_OWNER }} ${{ vars.DOMINO_PROJECT_NAME }} ${{ secrets.DOMINO_USER_API_KEY }} ${{ vars.DOMINO_API_HOST }} ${{ vars.DOMINO_HARDWARE_TIER }}
